-- DELETE FROM TeamParticipants;
-- DELETE FROM Team;
-- DELETE FROM Person;

CREATE TABLE IF NOT EXISTS Person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    age INT NULL,
    birthDate DATE NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    leader_id BIGINT REFERENCES Person(id),
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TeamParticipants (
    team_id BIGINT REFERENCES Team(id),
    participant_id BIGINT REFERENCES Person(id),
    PRIMARY KEY (team_id, participant_id)
);

-- Criar usuários se a tabela Person estiver completamente vazia
INSERT INTO Person (name, email, age, birthDate)
SELECT 'Líder 1', 'lider1@example.com', 30, '1990-01-01'
WHERE NOT EXISTS (SELECT 1 FROM Person);

INSERT INTO Person (name, email, age, birthDate)
SELECT 'Líder 2', 'lider2@example.com', 35, '1985-01-01'
WHERE NOT EXISTS (SELECT 1 FROM Person);

INSERT INTO Person (name, email, age, birthDate)
SELECT 'Integrante 1', 'integrante1@example.com', 25, '1995-01-01'
WHERE NOT EXISTS (SELECT 1 FROM Person);

INSERT INTO Person (name, email, age, birthDate)
SELECT 'Integrante 2', 'integrante2@example.com', 28, '1992-01-01'
WHERE NOT EXISTS (SELECT 1 FROM Person);

-- Criar equipes se a tabela Team estiver completamente vazia
INSERT INTO Team (name, email, leader_id)
SELECT 'Equipe 1', 'equipe1@example.com', 1
WHERE NOT EXISTS (SELECT 1 FROM Team);

INSERT INTO Team (name, email, leader_id)
SELECT 'Equipe 2', 'equipe2@example.com', 2
WHERE NOT EXISTS (SELECT 1 FROM Team);