
CREATE TABLE IF NOT EXISTS Person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    age INT NULL,
    birthDate DATE NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    leader_id BIGINT REFERENCES Person(id),
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TeamParticipants (
    team_id BIGINT REFERENCES Team(id),
    participant_id BIGINT REFERENCES Person(id),
    PRIMARY KEY (team_id, participant_id)
);

-- Inserir Pessoas
INSERT INTO Person (name, email, age, birthDate)
SELECT 'ADM', 'lider@example.com', 30, '1990-01-01' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Person WHERE name = 'ADM' AND email = 'lider@example.com');

INSERT INTO Person (name, email, age, birthDate)
SELECT 'João', 'joao@example.com', 25, '1995-02-15' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Person WHERE name = 'João' AND email = 'joao@example.com');

INSERT INTO Person (name, email, age, birthDate)
SELECT 'Maria', 'maria@example.com', 28, '1992-08-10' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Person WHERE name = 'Maria' AND email = 'maria@example.com');

INSERT INTO Person (name, email, age, birthDate)
SELECT 'testes', 'testes@example.com', 28, '1992-08-10' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Person WHERE name = 'testes' AND email = 'testes@example.com');

-- Inserir Times
INSERT INTO Team (name, email, leader_id)
SELECT 'ADMINISTRAÇÃO', 'equipe@example.com', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Team WHERE name = 'ADMINISTRAÇÃO' AND email = 'equipe@example.com');

INSERT INTO Team (name, email, leader_id)
SELECT 'Equipe Joaão', 'equipejao@example.com', 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Team WHERE name = 'Equipe Joaão' AND email = 'equipejao@example.com');

INSERT INTO Team (name, email, leader_id)
SELECT 'Equipe Maria', 'maria@example.com', 3 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM Team WHERE name = 'Equipe Maria' AND email = 'maria@example.com');

