
CREATE TABLE IF NOT EXISTS Person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    age INTEGER NULL,
    birthDate DATE NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    leader_id BIGINT REFERENCES Person(id),
    participants ARRAY,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Criar usuários
INSERT INTO Person (name, email, age, birthDate) VALUES
    ('Líder 1', 'lider1@example.com', 30, '1990-01-01'),
    ('Líder 2', 'lider2@example.com', 35, '1985-01-01'),
    ('Integrante 1', 'integrante1@example.com', 25, '1995-01-01'),
    ('Integrante 2', 'integrante2@example.com', 28, '1992-01-01');

-- Criar equipes
INSERT INTO Team (name, email, leader_id, participants) VALUES
    ('Equipe 1', 'equipe1@example.com', 1, ARRAY[2, 3]), -- Líder 1, Integrante 1, Integrante 2
    ('Equipe 2', 'equipe2@example.com', 2, ARRAY[3]);    -- Líder 2, Integrante 2;